do
$$
declare

    v_schema_name varchar(50) 	 := 'vms';
    c record;
    v_text 			 int = 1;
	v_multiline_text int = 2;
	v_number 		 int = 3;
	v_date 			 int = 4;
	v_datetime 		 int = 5;
	v_currency 		 int = 6;
	v_lookup 		 int = 7;
	v_boolean 		 int = 8;
	    
	    
--Column type enum - id: 5, label: 2, key: 1, boolean:4
	v_id          int = 5;
	v_label       int = 2;
	v_key         int = 1;
	v_col_boolean int = 4;
	v_col_text    int = 3;

begin
    
create table test_vms (
    id serial primary key,
    vms_type      numeric(21, 8),
    custom_attributes     jsonb
);

create table test_product_config (
    product_id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    	data_populated bool NULL,
    	institute_id varchar(255) NULL,
    	mandatory bool NULL,
    	product_type varchar(255) NULL,
    	profile_name varchar(255) NULL,
    	waiver_allowed bool NULL,
    	created_by varchar(255) null ,
         created_on  timestamptz,
         modified_by varchar(255) null,
         modified_on  timestamptz
);

insert into vms.properties (key, value, description)
values ('AA_DUMMY_TEST_CONFIG',
        '{
         "test_flag": {
         "dummy_flag": true
    }
    }',
    'Dummy Test Description'
);





end;

$$;